# Generated by Django 4.2.25 on 2025-11-06 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=149)),
                ('addingDate', models.DateTimeField(auto_now=True)),
                ('dateStart', models.DateTimeField(default=models.DateTimeField(auto_now=True))),
                ('dateEnd', models.DateTimeField(default=models.DateTimeField(auto_now=True))),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
