# Generated by Django 5.2.8 on 2025-11-12 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=149)),
                ('addingDate', models.DateTimeField(auto_now=True)),
                ('dateStart', models.DateTimeField(auto_now_add=True)),
                ('dateEnd', models.DateTimeField(auto_now_add=True)),
                ('taskIsComplete', models.BooleanField(default=False)),
                ('author', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
