# Generated by Django 4.2.25 on 2025-11-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='dateEnd',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='dateStart',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
