# Generated by Django 4.2.25 on 2025-11-12 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_note_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='dateEnd',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='note',
            name='dateStart',
            field=models.DateTimeField(),
        ),
    ]
