# Generated by Django 4.2.25 on 2025-11-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_note_dateend_alter_note_datestart'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='taskIsComplete',
            field=models.BooleanField(default=False),
        ),
    ]
