# Generated by Django 4.2.25 on 2025-11-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_note_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
